#!/usr/bin/env python

import sys, os, re
from subprocess import check_output

# Collect the parameters
#print sys.argv[1]
#print sys.argv[2]
#print sys.argv[3]

# Figure out which branch we're on
branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()
print "commit-msg: On branch '%s'" % branch

# Jenkins test
msg = check_output(['C:\Python36\python.exe', 'E:\PYTHON\jenkins\jenkinsApi.py', 'test', 'iide', branch]).strip()
print "Jenkins:'%s'" % msg

# Jenkins dev
msg = check_output(['C:\Python36\python.exe', 'E:\PYTHON\jenkins\jenkinsApi.py', 'dev', 'iide', branch]).strip()
print "Jenkins:'%s'" % msg

#sys.exit(1)
